name: outpassfaculty
description: "The CIT Outpass App is a mobile application designed to simplify the outpass request process for students residing in the Chennai Institute of Technology (CIT) college hostels."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  google_fonts: 6.1.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  firebase_messaging: ^14.7.19
  cloud_functions: ^4.6.8
  shared_preferences: ^2.2.2
  syncfusion_flutter_xlsio: ^24.2.9
  open_file: ^3.3.2
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  csv: ^6.0.0
  file_picker: ^6.2.0
  excel: ^4.0.2
  device_info_plus: ^9.1.2
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/app_icon.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  android: true
  ios: true
  image: "images/splash_icon.png"
  color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - images/splash_icon.png
    - images/google_logo.png
