// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByIP3nPa7vVVotVpftWxHfl8htVdm4BUU',
    appId: '1:543211493618:android:6b75b46cd2a52fb3f0586b',
    messagingSenderId: '543211493618',
    projectId: 'citchennai-outpass-project',
    storageBucket: 'citchennai-outpass-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS8ZgLrE_wGFnGMJ8zfexif0Z0gx37l_E',
    appId: '1:543211493618:ios:945b2fe650a799cdf0586b',
    messagingSenderId: '543211493618',
    projectId: 'citchennai-outpass-project',
    storageBucket: 'citchennai-outpass-project.appspot.com',
    androidClientId: '543211493618-08ej2pfp0nutosb2v38teho8g8ne0ciq.apps.googleusercontent.com',
    iosClientId: '543211493618-gs789o1imrnu8lujapq1bbmrsh3q4hgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.outpassfaculty',
  );
}
